export default [
  "a serene landscape",
  "a bustling street scene",
  "an abstract composition",
  "a detailed portrait",
  "a vibrant sunset",
  "a peaceful seascape",
  "a city skyline at night",
  "a close-up of a flower",
  "a majestic mountain range",
  "a lively music festival",
  "a quiet forest path",
  "a historic cityscape",
  "an artistic still life",
  "a wide river view",
  "an intricate mandala",
  "a festive parade",
  "a snowy village scene",
  "a starry night sky",
  "a bustling coffee shop",
  "a tranquil lake at dawn",
  "an old wooden bridge",
  "a colorful graffiti wall",
  "a busy farmer's market",
  "a medieval castle",
  "a cozy interior setting",
  "an autumnal park",
  "a modern abstract sculpture",
  "a desert landscape under the sun",
  "a dramatic thunderstorm",
  "a charming cobblestone street",
  "a high-tech cityscape",
  "a wildlife scene with deer",
  "an underwater coral reef",
  "a vibrant butterfly on a flower",
  "a rustic barn in a field",
  "a fantasy forest",
  "a galaxy far away",
  "a carnival at night",
  "a panoramic beach view",
  "a charming village square",
  "a snowy mountain peak",
  "a bustling airport terminal",
  "a traditional Japanese garden",
  "a neon-lit urban street",
  "a picturesque vineyard",
  "an ice-covered landscape",
  "a historic train station",
  "a lively children's playground",
  "a serene monastery",
  "an old library full of books",
  "a modern skyscraper",
  "an ancient temple",
  "a crowded sports stadium",
  "a peaceful yoga studio",
  "an elegant ballroom",
  "a busy construction site",
  "a quiet backyard garden",
  "a lively dance club",
  "an exotic tropical beach",
  "a wide-open prairie",
  "a grand opera house",
  "a bustling harbor",
  "a spooky haunted house",
  "a futuristic space station",
  "a lively classroom",
  "a busy restaurant kitchen",
  "a serene chapel",
  "a sunlit forest clearing",
  "a crowded subway train",
  "a traditional farmhouse",
  "a colorful children's room",
  "a high-speed train zooming by",
  "a small town during a festival",
  "a bustling newsroom",
  "an old-fashioned diner",
  "a state-of-the-art laboratory",
  "a busy mechanic's garage",
  "a peaceful meditation room",
  "a lively barbecue party",
  "a luxury yacht on the open sea",
  "a historic battlefield",
  "a busy vet clinic",
  "a high-end fashion runway",
  "a busy supermarket",
  "a cozy bed and breakfast",
  "a lively skateboard park",
  "a tranquil Zen garden",
  "a bustling fish market",
  "a high-stakes poker game",
  "a scenic hiking trail",
  "a grand royal palace",
  "a busy bee hive",
  "a crowded amusement park",
  "a detailed map of a fantasy world",
  "a high-tech command center",
  "a cozy mountain cabin",
  "a busy nail salon",
  "a lively jazz club",
  "a historic colonial town",
  "a mysterious cave system",
  "a traditional Chinese tea house",
  "a modern art gallery",
  "a bustling bakery",
  "a tranquil bird sanctuary",
  "a vibrant coral reef",
  "a lively pet store",
  "a peaceful riverside cottage",
  "a bustling flea market",
  "a scenic vineyard",
  "a high-energy fitness gym",
  "a historic lighthouse",
  "a colorful carnival ride",
  "a lively street food market",
  "a high-altitude mountain camp",
  "a tranquil koi pond",
  "a busy shipping port",
  "a vibrant night club",
  "a crowded beach during summer",
  "a spooky abandoned mansion",
  "a high-tech robotics lab",
  "a serene yoga retreat",
  "a busy bridal boutique",
  "a lively karaoke bar",
  "a historic western ghost town",
  "a mysterious enchanted forest",
  "a traditional Moroccan bazaar",
  "a modern digital workspace",
  "a bustling train station during rush hour",
  "a tranquil rooftop garden",
  "a vibrant digital art piece",
  "a lively indoor swimming pool",
  "a high-fashion photo shoot",
  "a serene monastery in the mountains",
  "a busy airport runway",
  "a lively university campus",
  "a historic pirate ship",
  "a mysterious alien landscape",
  "a traditional gypsy caravan",
  "a modern urban rooftop",
  "a bustling city park",
  "a tranquil water garden",
  "a high-speed race track",
  "a serene wildlife reserve",
  "a busy movie set",
  "a lively circus tent",
  "a historic steam train",
  "a mysterious underground city",
  "a traditional Korean hanok village",
  "a modern virtual reality space",
  "a bustling emergency room",
  "a tranquil spa retreat",
  "a high-energy rock concert",
  "a serene chapel in the countryside",
  "a busy industrial factory",
  "a lively street parade",
  "a historic Viking village",
  "a mysterious space nebula",
  "a traditional Thai floating market",
  "a modern co-working space",
  "a bustling skate park",
  "a tranquil monastery garden",
  "a high-stakes casino floor",
  "a serene winter lodge",
  "a busy comic book convention",
  "a lively open-air theatre",
  "a historic Victorian mansion",
  "a mysterious tropical island",
  "a traditional Indian wedding ceremony",
  "a modern metropolitan subway",
  "a bustling dog park",
  "a tranquil desert oasis",
  "a high-tech virtual meeting room",
  "a serene alpine ski resort",
  "a busy children's hospital ward",
  "a lively outdoor music festival",
  "a historic Roman colosseum",
  "a mysterious deep-sea trench",
  "a traditional African village",
  "a modern electric car showroom",
  "a bustling bridge during rush hour",
  "a tranquil Japanese onsen",
  "a high-adrenaline bungee jump spot",
  "a serene butterfly conservatory",
  "a busy craft fair",
  "a lively salsa dance club",
  "a historic European cathedral",
  "a mysterious abandoned space station",
  "a traditional Hawaiian luau",
  "a modern urban art installation",
  "a bustling mountain ski resort",
  "a tranquil herb garden",
  "a high-tech surveillance center",
  "a serene rainforest canopy walk",
  "a busy tattoo studio",
  "a lively street basketball game",
  "a historic medieval market",
  "a mysterious foggy moor",
  "a traditional Venetian gondola",
  "a modern nuclear power plant",
  "a bustling city during a holiday celebration",
  "a tranquil monastery library",
  "a high-energy dance studio",
  "a serene orchid greenhouse",
  "a busy art studio",
  "a lively Brazilian carnival",
  "a historic Egyptian pyramid",
  "a mysterious abandoned asylum",
  "a traditional Japanese sumo wrestling match",
  "a modern glassblowing studio",
  "a bustling seafood restaurant",
  "a tranquil English cottage garden",
  "a high-octane drag race",
  "a serene temple in the Himalayas",
  "a busy urban bike path",
  "a lively Mardi Gras parade",
  "a historic Spanish galleon",
  "a mysterious black hole in space",
  "a traditional Bedouin camp",
  "a modern high-rise apartment interior",
  "a bustling metro during peak hours",
  "a tranquil tulip field in bloom",
  "a high-tech startup office",
  "a serene Balinese temple",
  "a busy florist shop",
  "a lively tapas bar",
  "a historic American diner",
  "a mysterious sunken city",
  "a traditional Chinese dragon boat race",
  "a modern minimalist home",
  "a bustling boxing gym",
  "a tranquil alpine meadow",
  "a high-end designer boutique",
  "a serene forest during autumn",
  "a busy pottery studio",
  "a lively Oktoberfest celebration",
  "a historic Greek amphitheater",
  "a mysterious planet in a distant galaxy",
  "a traditional Scottish Highland games",
  "a modern city during a tech convention",
  "a bustling airport check-in area",
  "a tranquil vine-covered pergola",
  "a high-octane motocross race",
  "a serene island at sunset",
  "a busy knitting circle",
  "a lively roller disco",
  "a historic samurai village",
  "a mysterious time-travel portal",
  "a traditional Mexican Day of the Dead festival",
  "a modern minimalist office space",
  "a bustling indoor shopping mall",
  "a tranquil morning in a bakery",
  "a high-altitude helicopter tour",
  "a serene Buddhist temple",
  "a busy auto repair shop",
  "a lively beach volleyball game",
  "a historic Renaissance fair",
  "a mysterious lost city in the jungle",
  "a traditional Russian ballet performance",
  "a modern urban green space",
  "a bustling sushi bar",
  "a tranquil yoga class in a park",
  "a high-powered corporate boardroom",
  "a serene winter wonderland",
  "a busy pet grooming salon",
  "a lively African drum circle",
  "a historic colonial-era fort",
  "a mysterious interstellar spacecraft",
  "a traditional German beer garden",
  "a modern 3D printing lab",
  "a bustling hot dog stand in New York",
  "a tranquil butterfly garden",
  "a high-speed Formula 1 race",
  "a serene traditional tea ceremony",
  "a busy local farmers market",
  "a lively carnival in Rio",
  "a historic steam-powered locomotive",
  "a mysterious ancient temple in the jungle",
  "a traditional Irish pub",
  "a modern wind farm",
  "a bustling street in Hong Kong",
  "a tranquil morning on a fishing boat",
  "a high-energy aerobics class",
  "a serene chapel in a small village",
  "a busy urban graffiti wall",
  "a lively tap dancing class",
  "a historic castle in Scotland",
  "a mysterious underground bunker",
  "a traditional Turkish bathhouse",
  "a modern urban loft apartment",
  "a bustling artisan cheese shop",
  "a tranquil waterfall in a forest",
  "a high-adrenaline skydiving jump",
  "a serene mountain hot spring",
  "a busy gourmet food truck",
  "a lively drum and bass club night",
  "a historic American railroad",
  "a mysterious crystal cave",
  "a traditional Italian vineyard",
  "a modern esports gaming arena",
  "a bustling street in Tokyo",
  "a tranquil country road at sunrise",
  "a high-speed bullet train in Japan",
  "a serene monastery in Tibet",
  "a busy airport baggage claim",
  "a lively New Year's Eve party",
  "a historic Dutch windmill",
  "a mysterious alien landscape on Mars",
  "a traditional Korean barbecue restaurant",
  "a modern city bike-sharing station",
  "a bustling college library during finals",
  "a tranquil morning yoga session",
  "a high-intensity boxing match",
  "a serene Japanese Zen rock garden",
  "a busy artisanal bakery",
  "a lively salsa dancing competition",
  "a historic Gothic cathedral",
];
